nodeLinker: pnp

packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.13.10
  html-webpack-plugin@*:
    dependencies:
      loader-utils: ^2.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
